# Generated by Django 3.2.13 on 2022-12-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='postType',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
