# Generated by Django 3.2.13 on 2022-12-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_postmodel_posttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='postStatus',
            field=models.CharField(default='Pending', max_length=50, null=True),
        ),
    ]
