# Generated by Django 3.2.13 on 2022-12-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_postmodel_poststatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimowner',
            name='claimerPostId',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
