# Generated by Django 3.2.13 on 2022-12-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_claimowner_postfileimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claimowner',
            old_name='claimerId',
            new_name='foundPostId',
        ),
        migrations.RenameField(
            model_name='claimowner',
            old_name='claimFileImg',
            new_name='foundPostImg',
        ),
        migrations.RenameField(
            model_name='claimowner',
            old_name='claimerEmail',
            new_name='foundPostUserEmail',
        ),
        migrations.RenameField(
            model_name='claimowner',
            old_name='claimerPostId',
            new_name='foundPostUserId',
        ),
        migrations.RenameField(
            model_name='claimowner',
            old_name='claimerName',
            new_name='foundPostUserName',
        ),
        migrations.RenameField(
            model_name='claimowner',
            old_name='postId',
            new_name='lostPostId',
        ),
        migrations.RenameField(
            model_name='claimowner',
            old_name='postFileImg',
            new_name='lostPostImg',
        ),
        migrations.RenameField(
            model_name='claimowner',
            old_name='postPunlisherEmail',
            new_name='lostPostUserEmail',
        ),
        migrations.RenameField(
            model_name='claimowner',
            old_name='postPunlisherName',
            new_name='lostPostUserName',
        ),
        migrations.RemoveField(
            model_name='claimowner',
            name='status',
        ),
        migrations.AddField(
            model_name='claimowner',
            name='foundPostDescription',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='claimowner',
            name='foundPostTittle',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='claimowner',
            name='lostPostDescription',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='claimowner',
            name='lostPostTittle',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='claimowner',
            name='lostPostUserId',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
